application: tweetux42
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  
- url: /tweets/.*
  script: main.py

- url: /js/tweets
  script: main.py
  
- url: /oauth/twitter/(.*)
  script: main.py
  
- url: /status/update
  script: main.py

- url: /profile/\w+
  script: main.py

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico